print("Select a language/Выберите язык")
a = input('Eng=2/Рус=1:')
if a == '1':
    print('Выберите язык программирования, азы которого вы хотите узнать')
    b = input('Python = 1/C++ = 2/JavaScript = 3')
    if b == '1':
        while True:
            print('Выберите тему: ')
            c = input('print() = 1/input() = 2/While = 3/if = 4/for = 5/break = 6/ end = 7/count = 8/ int() = 9/ and-or = 10/ задачи на праткику - practice')
            if c == '1':
                print('print() — Вывод информации на экран')
                print('Зачем нужен? Чтобы программа показывала текст, числа или результаты вычислений.')
                print('Как работает? Вы пишете print(), а внутрь скобок помещаете то, что хотите вывести.')
                print('Простые примеры:')
                print('print(2026)')
                print('Несколько значений сразу: Перечислите их через запятую.')
                print('Соединение текста (конкатенация): Используйте +, но не смешивайте строки и числа.')
            if c == '2':
                input('Заметим, что в каждой теме используется именно та команда, тема которой изучается. Для продолжения нажмите Enter')
                input('input() — Ввод информации от пользователя')
                input('Зачем нужен? Чтобы программа могла спросить что-то у пользователя и запомнить ответ.')
                input('Как работает? Программа ставится на паузу, ждет, пока пользователь введет текст и нажмет Enter. Введенные данные всегда возвращаются в виде строки (text).')
                input('Простой пример:')
                input('user_name = input("Как тебя зовут? ")')
                input('print("Рад познакомиться, " + user_name + "!")')
                input('Важное правило:')
                input('input() всегда возвращает строку. Даже если вы ввели число.')
                input('age = input("Сколько тебе лет? ")')
                input('print(type(age))')
                input('age_number = int(age)')
                input('print("В следующем году тебе будет", age_number + 1)')
                input('Можно сразу преобразовать ввод:')
                input('age = int(input("Сколько тебе лет? "))')
            if c == '3':
                print('Заметим, что весь код зациклен имеенно while True')
                print('while — Цикл «Пока»')
                print('Зачем нужен? Чтобы повторять один и тот же блок кода много раз, пока выполняется какое-то условие.')
                print('Как работает? Пока условие после слова while истинно (True), команды внутри цикла выполняются снова и снова.')
            if c == '4':
                print('if — это страж-регулировщик в коде.')
                print('Он задаёт вопрос, на который можно ответить только «да» (True) или «нет» (False).')
                print('Как работает:')
                print('Программа проверяет условие после слова if.')
                print('Если ответ «да», выполняется блок команд под ним (выделенный отступами).')
                print('Если «нет», этот блок пропускается.')
                print('Дополнительные пути:')
                print('else («иначе») — что делать, если ответ «нет».')
                print('elif («а если…») — для проверки цепочки условий. Проверяет их по порядку и останавливается на первом верном.')
                print('Что считается «да»? Почти всё:')
                print('любые числа кроме нуля, непустой текст, непустые списки.')
                print('Что «нет»?')
                print('False, 0, пустая строка "", пустой список [], None.')
                print('Проще говоря, if — это основа для принятия решений в программе.')
                print('Теперь покажем на практике')
                print('Сейчас в коде будет выведена команда if с выбором числа. При вводе 1 будет выдан +.')
                print('При любом другом исходе будет выдан -')
                k = input('Введите число: ')
                if k == '1':
                    print('+')
                else:
                    print('-')
            if c == '5':
                print('Цикл for — это конвейер или автоматический переборщик.')
                print('Он берёт коллекцию элементов (например, список, строку или диапазон чисел) и поочерёдно, один за другим, передаёт каждый элемент в тело цикла для выполнения одних и тех же действий.')
                print('Как работает:')
                print('Подготовка: Тебе нужен «контейнер» с элементами (например, список [1, 2, 3] или строка "привет").')
                print('Запуск: Цикл for открывает контейнер, берёт первый элемент и временно присваивает его переменной (например, item или i).')
                print('Выполнение: Программа выполняет всё, что написано в блоке цикла (с отступом), используя этот текущий элемент.')
                print('Повтор: Затем цикл автоматически переходит к следующему элементу в контейнере и повторяет шаг 3.')
                print('Завершение: Этот процесс продолжается, пока все элементы в контейнере не будут перебраны. Когда элементы заканчиваются, цикл завершается, и программа идёт дальше.')
                print('Простая аналогия:')
                print('Это как автоматический почтальон, который берёт пачку писем (список) и раз за разом совершает однотипное действие:')
                print('достаёт очередное письмо (элемент) из пачки и кладёт его в почтовый ящик (выполняет код в теле цикла).')
                print('Он останавливается, когда пачка становится пустой.')
                print('Сейчас посмотрим как работает этот цикл на практике')
                print('Сейчас нужно будет ввести число. Цикл напишет фразу "Hello World!" нужное кол-во раз')
                k = int(input('Введите число: '))
                for i in range(k):
                    print('Hello World!')
            if c == '6':
                print('break — это аварийный выход или кнопка «стоп» внутри цикла (for или while).')
                print('Он мгновенно и полностью прерывает выполнение всего цикла, даже если в нём ещё остались необработанные элементы или условие для продолжения работы всё ещё истинно.')
                print('Как работает:')
                print('Цикл работает в обычном режиме.')
                print('В какой-то момент внутри цикла срабатывает условие с командой break.')
                print('Немедленно выполнение цикла прекращается.')
                print('Управление передаётся следующей строке кода после цикла.')
                print('Простая аналогия:')
                print('Представь, что ты перебираешь коробку с яблоками в поисках гнилого.')
                print('Цикл — это процесс проверки каждого яблока по порядку.')
                print('Как только ты находишь первое гнилое яблоко, команда break заставляет тебя сразу выбросить всю коробку (прервать цикл), не проверяя оставшиеся яблоки.')
                print('Главное:')
                print('После break цикл не просто пропускает один шаг — он завершается навсегда.')
                print('Сейчас проверим break на практике. Запустим цикл for и прервем его с помощью break')
                print('Заметить вы его сможете в коде программы')
                k = int(input('Введите число: '))
                for i in range(k):
                    print('Сейчас цикл прервется')
                    break
            if c == '7':
                print('end в функции print() — это невидимый символ, который печатается после всего текста.')
                print(
                    "По умолчанию end='\n' — это перенос строки. Поэтому каждый новый print() начинается с новой строки.")
                print(
                    'Если задать end=' ' (пробел), то следующий print() продолжит вывод в той же строке через пробел.')
                print('Если задать end='' (пустая строка), вывод склеится вплотную.')
                print('Пример:')
                print("print('При', end='вет') выведет просто «Привет» без перехода на новую строку.")
                print('Пример: в этом моменте в коде вы сможете посмотреть, как это работает.')
                print('При', end='вет')
            if c == '8':
                print('count() — это счётчик вхождений.')
                print('Это метод для строк, списков и кортежей.')
                print('Он отвечает на вопрос: «Сколько раз этот конкретный элемент встречается внутри коллекции?»')
                print('Как работает:')
                print('Ты указываешь коллекцию (например, строку или список).')
                print('Передаёшь в count() искомый элемент (символ, слово, число).')
                print('Метод проходит по всей коллекции и возвращает число — сколько раз он нашёл точное совпадение.')
                print('Пример из жизни:')
                print('У тебя есть предложение "кот ловит котят".')
                print('Спроси у него: count("кот")')
                print('Оно ответит: 2 (слово «кот» встречается два раза).')
                print('Важно:')
                print('Он ищет точные совпадения и учитывает регистр («Кот» и «кот» — разные).')
                print('Пример: сейчас нужно будет ввести комбинацию "aabbcc". Код выведет нам кол-во букв "b"')
                k = input('Введите слово: ')
                l = k.count("b")
                print(l)
            if c == '9':
                print('int() в Python')
                print('Что: Функция для работы с целыми числами.')
                print('Основное:')
                print('Преобразует строки в числа: "25" → 25')
                print('Отбрасывает дробную часть: 3.14 → 3')
                print('Работает с разными системами счисления (двоичная, шестнадцатеричная)')
                print('Зачем:')
                print('Делать математику с вводом пользователя')
                print('Считать, индексировать, выполнять вычисления')
                print('Превращать текст в работающие числа')
                print('Важно:')
                print('Только цифры, без букв')
                print('При ошибке — программа падает')
                print('input() даёт строку → нужен int() для вычислений')
                print('Пример: возраст = int(input("Сколько лет?"))')
                print('Пример в коде: int() же появлялся в коде например в отделе про break. Покажем на подобном примере: ')
                k = int(input('<Напишите свой возраст: '))
                print('Вам',k,'лет')
            if c == '10':
                print('and и or — ЛОГИЧЕСКИЕ ОПЕРАТОРЫ В PYTHON')
                print('Что: Операторы для комбинирования условий.')
                print('Основное:')
                print('and — логическое "И" (оба условия истинны)')
                print('or — логическое "ИЛИ" (хотя бы одно условие истинно)')
                print('Работают с любыми типами, возвращают последнее проверенное значение')
                print('Используются в условиях if, while')
                print('Как работают:')
                print('and — проверяет слева направо:')
                print('Если ЛЕВЫЙ операнд False → сразу возвращает его')
                print('Если ЛЕВЫЙ True → возвращает ПРАВЫЙ операнд')
                print('or — проверяет слева направо:')
                print('Если ЛЕВЫЙ операнд True → сразу возвращает его')
                print('Если ЛЕВЫЙ False → возвращает ПРАВЫЙ операнд')
                print('Зачем:')
                print('Комбинировать несколько проверок в одном условии')
                print('Создавать сложную логику программ')
                print('Проверять диапазоны значений')
                print('Обрабатывать альтернативные случаи')
                print('Важно:')
                print('Приоритет: not > and > or')
                print('Используйте скобки для сложных выражений')
                print('Можно комбинировать: (a or b) and c')
                print('Работают с любыми значениями, не только True/False')
                print('Пример будет показан на примере or. Сейчас нужно будет ввести 2 числа. Любое из них должно быть выше 5.')
                print('Если они оба больще 5 код выведет "1"')
                print('Если только одно число больше 5 код выведет "0"')
                print('Если же оба числа меньше 5 код выведет "-1"')
                k = int(input('Введите первое число: '))
                l = int(input('Введите второе число: '))
                if k > 5 or l > 5:
                    print('0')
                elif k > 5 and l > 5:
                    print('1')
                else:
                    print('-1')
            if c == 'practice':
                print('Выберите задачу')
                print('Примечание: решать задачу нужно в отдельной программе (например Pycharm или VS code)')
                k = input('калькулятор суммы двух чисел = 1/проверка возраста = 2/счетчик числа 1 - n = 3/проверка пароля = 4 ')
                if k == '1':
                    print('КАЛЬКУЛЯТОР СУММЫ ДВУХ ЧИСЕЛ')
                    print('Задание: ')
                    print('Напишите программу, которая запрашивает у пользователя два целых числа и выводит их сумму.')
                    input('Для проверки и получениия готового кода нажмите Enter')
                    print('num1 = int(input("Введи первое число: "))')
                    print('num2 = int(input("Введи второе число: "))')
                    print('result = num1 + num2')
                    print('print("Сумма:", result)')
                if k == '2':
                    print('ПРОВЕРКА ВОЗРАСТА')
                    print('Задание:')
                    print('Создайте программу, которая определяет, совершеннолетний ли пользователь на основе введённого возраста.')
                    input('Для проверки и получениия готового кода нажмите Enter')
                    print('age = int(input("Сколько тебе лет? "))')
                    print('if age >= 18:')
                    print('     print("Ты совершеннолетний")')
                    print('else:')
                    print('     print("Ты несовершеннолетний")')
                if k == '3':
                    print('СЧЁТЧИК ОТ 1 ДО N')
                    print('Задание:')
                    print('Выведите все числа от 1 до N, где N вводит пользователь.')
                    input('Для проверки и получениия готового кода нажмите Enter')
                    print('n = int(input("Введи число: "))')
                    print('for i in range(1, n + 1):')
                    print('     print(i)')
                if k == '4':
                    print('ПРОВЕРКА ПАРОЛЯ')
                    print('Задание:')
                    print('Реализуйте простую проверку пароля — доступ разрешён только при вводе правильного пароля.')
                    input('Для проверки и получениия готового кода нажмите Enter')
                    print('password = "12345"')
                    print('user_input = input("Введи пароль: ")')
                    print('if user_input == password:')
                    print('     print("Доступ разрешён")')
                    print('else:')
                    print('     print("Неверный пароль")')
            else:
                print('ERROR')
    if b == '2':
        while True:
            print('Выберите тему')
            c = input('БАЗОВЫЙ СИНТАКСИС = 1/ПЕРЕМЕННЫЕ И ТИПЫ ДАННЫХ = 2/ВВОД ДАННЫХ = 3/ #include = 4')
            if c == '1':
                print('БАЗОВЫЙ СИНТАКСИС')
                print('Каждая программа на C++ состоит из обязательных элементов.')
                print('Сначала подключаются библиотеки — наборы готовых функций, например iostream для ввода и вывода.')
                print('Затем указывается пространство имен std, чтобы не писать его перед каждой командой.')
                print('Главная часть программы — функция main(), которая выполняется первой.')
                print('Весь код пишется внутри фигурных скобок этой функции.')
                print('В конце программа возвращает 0, что означает успешное завершение.')
                print('Для вывода информации на экран используется команда cout с оператором <<.')
                print('Текст выводится в двойных кавычках.')
                print('Для перехода на новую строку используется endl.')
                print('Команды разделяются точкой с запятой.')
            if c == '2':
                print('ПЕРЕМЕННЫЕ И ТИПЫ ДАННЫХ')
                print('Переменные — это именованные ячейки памяти для хранения данных.')
                print('Каждая переменная имеет тип, имя и значение.')
                print('Тип определяет, какие данные можно хранить и сколько места они занимают.')
                print('Основные типы данных:')
                print('Целые числа: int для обычных чисел, short для маленьких, long для больших')
                print('Дробные числа: float с обычной точностью, double с двойной точностью')
                print('Символы: char хранит один символ в одинарных кавычках')
                print('Логические значения: bool хранит true (истина) или false (ложь)')
                print('Строки: string хранит текст в двойных кавычках')
                print('Имена переменных должны начинаться с буквы или подчеркивания, содержать только буквы, цифры и подчеркивания.')
                print('Содержать только буквы, цифры и подчеркивания. Регистр имеет значение.')
            if c == '3':
                print('Для получения данных от пользователя используется команда cin с оператором >>.')
                print('Программа ждет, пока пользователь введет данные и нажмет Enter.')
                print('Можно считывать числа, символы и строки.')
                print('При считывании строк есть нюансы:')
                print('cin считывает только до первого пробела.')
                print('Для чтения целой строки с пробелами используется getline().')
                print('Важно:')
                print('cin и cout работают через буфер — временное хранилище данных.')
                print('При вводе чисел нужно быть внимательным, так как после них в буфере может оставаться символ новой строки.')
            if c == "4":
                print('#include — ПОДКЛЮЧЕНИЕ БИБЛИОТЕК В C++')
                print('Что: Директива для подключения внешних библиотек.')
                print('Основное:')
                print('Добавляет готовые функции в программу')
                print('Без неё не работают cout, cin, string')
                print('Пишется в самом начале файла')
                print('Зачем:')
                print('Использовать стандартные функции C++')
                print('Работать с вводом/выводом')
                print('Добавлять математические операции')
                print('Использовать контейнеры и алгоритмы')
                print('Важно:')
                print('Угловые скобки для стандартных библиотек: #include <iostream>')
                print('Кавычки для своих файлов: #include "myfile.h"')
                print('Каждая библиотека — отдельная директива')
                print('Порядок не важен, но лучше логически группировать')
                print('Примеры библиотек:')
                print('<iostream> — ввод/вывод')
                print('<string> — работа со строками')
                print('<cmath> — математические функции')
                print('<vector> — динамические массивы')
            else:
                print('ERROR')
#Тут у человека смотрящего код может созреть вопрос почему так много print().
#Я знаю, что сущесвтует end = "\n"
#Во первых новичку в таком формате будет проще понять смысл print() и input()
#Во вторых
#В таком виде код мне нравится больше
    if b == '3':
        while True:
            print('Выберите тему')
            c = input('console.log() = 1/let / const = 2/prompt() / alert() = 3/ if - else = 4/for = 5')
            if c == '1':
                print('console.log() — ВЫВОД ИНФОРМАЦИИ')
                print('Что это: Самая первая команда, которую изучают в JavaScript.')
                print('Служит для вывода информации в консоль браузера или терминал Node.js.')
                print('Зачем нужна:')
                print('Отладка кода (проверка значений переменных)')
                print('Вывод результатов работы программы')
                print('Сообщения об ошибках или событиях')
                print('Как работает:')
                print('Принимает любое количество аргументов и выводит их в консоль.')
                print('Аргументы преобразуются в строки, если это необходимо.')
                print('Особенности:')
                print('Не прерывает выполнение программы')
                print('Может выводить любые типы данных')
                print('В браузере открывается через Инструменты разработчика (F12)')
            if c == '2':
                print('let / const — ОБЪЯВЛЕНИЕ ПЕРЕМЕННЫХ')
                print('Что это: Ключевые слова для создания переменных.')
                print('let — для изменяемых значений, const — для неизменяемых (констант).')
                print('Зачем нужны:')
                print('Хранение данных в памяти')
                print('Повторное использование значений')
                print('Улучшение читаемости кода')
                print('Как работают:')
                print('let позволяет менять значение переменной')
                print('Область видимости — блок кода (фигурные скобки)')
                print('Особенности:')
                print('Раньше использовался var (устаревший, имеет другую область видимости)')
                print('const не делает объекты неизменяемыми, только защищает от переприсваивания')
                print('Переменные объявляются до использования')
            if c == '3':
                print('prompt() / alert() — ВЗАИМОДЕЙСТВИЕ С ПОЛЬЗОВАТЕЛЕМ')
                print('Что это: Команды для простого диалога с пользователем в браузере.')
                print('alert() — вывод сообщения:')
                print('Показывает модальное окно с сообщением')
                print('Пользователь должен нажать OK для продолжения')
                print('Используется для важных уведомлений')
                print('prompt() — ввод данных:')
                print('Показывает окно с полем для ввода текста')
                print('Возвращает введенную строку или null при отмене')
                print('Всегда возвращает строку, даже если введено число')
                print('Зачем нужны:')
                print('Быстрое тестирование взаимодействия')
                print('Простейшие формы ввода')
                print('Демонстрационные примеры')
                print('Особенности:')
                print('Блокируют выполнение JavaScript до ответа пользователя')
                print('Дизайн зависит от браузера')
                print('В реальных проектах используются редко (предпочитают HTML-формы)')
            if c == '4':
                print('if...else — УСЛОВИЯ В JAVASCRIPT')
                print('Что: Конструкция для принятия решений в коде.')
                print('Зачем: Заставить программу выполнять разный код в зависимости от ситуации.')
                print('Как:')
                print('if проверяет условие')
                print('Если условие true → выполняется код в {}')
                print('Если false и есть else → выполняется код после else')
                print('Можно цепочку: if → else if → else')
                print('Особенности:')
                print('=== сравнивает строго (тип и значение)')
                print('== сравнивает с преобразованием типов')
                print('&& (И), || (ИЛИ), ! (НЕ) для сложных условий')
                print('Почему важно:')
                print('Без условий код только линейный.')
                print('С if...else программа становится "умной" и реагирует на данные.')
            if c == '5':
                print('for — ЦИКЛ ПЕРЕБОРА В JAVASCRIPT')
                print('Что: Цикл для последовательного перебора элементов.')
                print('Основное:')
                print('Перебирает массивы, строки, объекты')
                print('Работает с итераторами (списками элементов)')
                print('Автоматически проходит все элементы от начала до конца')
                print('Зачем:')
                print('Обработать каждый элемент массива')
                print('Пройти по всем символам строки')
                print('Выполнить действие для набора данных')
                print('Автоматизировать повторяющиеся операции')
                print('Важно:')
                print('Не путать с for в C++/Python — синтаксис другой')
                print('Чаще используется для массивов, чем while')
                print('Можно прервать break или пропустить итерацию continue')
            else:
                print('ERROR')
    else:
        print('ERROR')

if a == '2':
    print('Choose a programming language you want to learn the basics of')
    b = input('Python = 1/C++ = 2/JavaScript = 3')
    if b == '1':
        while True:
            print('Choose a topic')
            c = input('print() = 1/input() = 2/While = 3/if = 4/for = 5/break = 6/ end = 7/count = 8/ int() = 9/ and-or = 10')
            if c == '1':
                print('print() — Outputting information to the screen')
                print('What is it for? To make the program display text, numbers, or calculation results.')
                print('How does it work? You write print(), and inside the parentheses you put what you want to output.')
                print('Simple examples:')
                print('print(2026)')
                print('Multiple values at once: List them separated by commas.')
                print('Text concatenation: Use +, but do not mix strings and numbers.')
            if c == '2':
                input('Note that each topic uses the command that is being studied. Press Enter to continue')
                input('input() — Getting input from the user')
                input('What is it for? So that the program can ask the user something and remember the answer.')
                input('How does it work? The program pauses, waits for the user to enter text and press Enter. The entered data is always returned as a string (text).')
                input('Simple example:')
                input('user_name = input("What is your name? ")')
                input('print("Nice to meet you, " + user_name + "!")')
                input('Important rule:')
                input('input() always returns a string. Even if you entered a number.')
                input('age = input("How old are you? ")')
                input('print(type(age))')
                input('age_number = int(age)')
                input('print("Next year you will be", age_number + 1)')
                input('You can convert input immediately:')
                input('age = int(input("How old are you? "))')
            if c == '3':
                print('Note that the entire code is looped with while True')
                print('while — The "While" Loop')
                print('What is it for? To repeat the same block of code many times as long as some condition is true.')
                print('How does it work? As long as the condition after the word while is true (True), the commands inside the loop are executed again and again.')
            if c == '4':
                print('if is a guard traffic controller in the code.')
                print('It asks a question that can only be answered with "yes" (True) or "no" (False).')
                print('How it works:')
                print('The program checks the condition after the word if.')
                print('If the answer is "yes", the block of commands under it (indented) is executed.')
                print('If "no", this block is skipped.')
                print('Additional paths:')
                print('else ("otherwise") — what to do if the answer is "no".')
                print(
                    'elif ("what if...") — for checking a chain of conditions. Checks them in order and stops at the first true one.')
                print('What is considered "yes"? Almost everything:')
                print('any numbers except zero, non-empty text, non-empty lists.')
                print('What is "no"?')
                print('False, 0, empty string "", empty list [], None.')
                print('Simply put, if is the foundation for decision-making in a program.')
                print("Now let's demonstrate in practice")
                print('The code will now output an if command with a number choice. If you enter 1, it will output +.')
                print('For any other input, it will output -')
                k = input('Enter a number: ')
                if k == '1':
                    print('+')
                else:
                    print('-')
            if c == '5':
                print('The for loop is a conveyor belt or an automatic enumerator.')
                print(
                    'It takes a collection of elements (e.g., a list, a string, or a range of numbers) and sequentially, one by one, passes each element into the loop body to perform the same actions.')
                print('How it works:')
                print('Preparation: You need a "container" with elements (e.g., a list [1, 2, 3] or a string "hello").')
                print(
                    'Start: The for loop opens the container, takes the first element, and temporarily assigns it to a variable (e.g., item or i).')
                print(
                    'Execution: The program executes everything written in the loop block (indented), using this current element.')
                print(
                    'Repeat: Then the loop automatically moves to the next element in the container and repeats step 3.')
                print(
                    'Completion: This process continues until all elements in the container have been iterated. When the elements run out, the loop finishes, and the program continues.')
                print('Simple analogy:')
                print(
                    'It’s like an automatic mail carrier who takes a stack of letters (a list) and repeatedly performs the same action:')
                print(
                    'takes the next letter (element) from the stack and puts it into a mailbox (executes the code in the loop body).')
                print('They stop when the stack is empty.')
                print('Now let’s see how this loop works in practice')
                print(
                    'You’ll now need to enter a number. The loop will print the phrase "Hello World!" the specified number of times')
                k = int(input('Enter a number: '))
                for i in range(k):
                    print('Hello World!')
            if c == '6':
                print('break is an emergency exit or "stop" button inside a loop (for or while).')
                print(
                    'It instantly and completely interrupts the execution of the entire loop, even if there are still unprocessed elements or the condition for continuing is still true.')
                print('How it works:')
                print('The loop operates normally.')
                print('At some point inside the loop, a condition with the break command is triggered.')
                print('Immediately, the loop execution stops.')
                print('Control is transferred to the next line of code after the loop.')
                print('Simple analogy:')
                print('Imagine you are going through a box of apples looking for a rotten one.')
                print('The loop is the process of checking each apple in order.')
                print(
                    'As soon as you find the first rotten apple, the break command forces you to immediately throw away the entire box (interrupt the loop) without checking the remaining apples.')
                print('Main point:')
                print('After break, the loop doesn\'t just skip one step — it ends forever.')
                print('Now let\'s test break in practice. Let\'s run a for loop and interrupt it using break')
                print('You will be able to notice it in the program code')
                k = int(input('Enter a number: '))
                for i in range(k):
                    print('The loop will now break')
                    break
            if c == '7':
                print('end in the print() function is an invisible character that is printed after all the text.')
                print("By default end='\n' — this is a line break. Therefore, each new print() starts on a new line.")
                print(
                    'If you set end=' ' (a space), then the next print() will continue output on the same line with a space.')
                print('If you set end='' (an empty string), the output will be concatenated directly.')
                print('Example:')
                print("print('Hello', end='World') will simply output «HelloWorld» without moving to a new line.")
                print('Example: at this point in the code you will be able to see how it works.')
                print('Hello', end='World')
            if c == '8':
                print('count() is an occurrence counter.')
                print('It is a method for strings, lists, and tuples.')
                print(
                    'It answers the question: "How many times does this specific element appear inside the collection?"')
                print('How it works:')
                print('You specify a collection (for example, a string or list).')
                print('Pass the sought element (character, word, number) to count().')
                print(
                    'The method goes through the entire collection and returns a number — how many times it found an exact match.')
                print('Real-life example:')
                print('You have the sentence "cat catches kittens".')
                print('Ask it: count("cat")')
                print('It will answer: 2 (the word "cat" appears twice).')
                print('Important:')
                print('It looks for exact matches and is case-sensitive ("Cat" and "cat" are different).')
                print(
                    'Example: now you need to enter the combination "aabbcc". The code will output the number of letters "b"')
                k = input('Enter a word: ')
                l = k.count("b")
                print(l)
            if c == '9':
                print('int() in Python')
                print('What: A function for working with integers.')
                print('Main functions:')
                print('Converts strings to numbers: "25" → 25')
                print('Discards the fractional part: 3.14 → 3')
                print('Works with different numeral systems (binary, hexadecimal)')
                print('Why use it:')
                print('To perform math with user input')
                print('To count, index, and perform calculations')
                print('To turn text into functional numbers')
                print('Important:')
                print('Only digits, no letters')
                print('On error — the program crashes')
                print('input() gives a string → int() is needed for calculations')
                print('Example: age = int(input("How old are you?"))')
                print('Code example: int() has already appeared in code, for example, in the section about break. Let’s demonstrate with a similar example:')
                k = int(input('Enter your age: '))
                print('You are', k, 'years old')
            if c == '10':
                print('and and or — LOGICAL OPERATORS IN PYTHON')
                print('What: Operators for combining conditions.')
                print('Main features:')
                print('and — logical "AND" (both conditions true)')
                print('or — logical "OR" (at least one condition true)')
                print('Work with any types, return the last evaluated value')
                print('Used in if, while conditions')
                print('How they work:')
                print('and — evaluates left to right:')
                print('If the LEFT operand is False → returns it immediately')
                print('If the LEFT operand is True → returns the RIGHT operand')
                print('or — evaluates left to right:')
                print('If the LEFT operand is True → returns it immediately')
                print('If the LEFT operand is False → returns the RIGHT operand')
                print('Purpose:')
                print('To combine multiple checks into one condition')
                print('To create complex program logic')
                print('To check value ranges')
                print('To handle alternative cases')
                print('Important:')
                print('Precedence: not > and > or')
                print('Use parentheses for complex expressions')
                print('Can be combined: (a or b) and c')
                print('Work with any values, not just True/False')
                print(
                    'An example will be shown using or. Now you will need to enter 2 numbers. Either of them must be greater than 5.')
                print('If both are greater than 5, the code will output "1"')
                print('If only one number is greater than 5, the code will output "0"')
                print('If both numbers are less than 5, the code will output "-1"')
                k = int(input('Enter the first number: '))
                l = int(input('Enter the second number: '))
                if k > 5 or l > 5:
                    print('0')
                elif k > 5 and l > 5:
                    print('1')
                else:
                    print('-1')
            if c == 'practice':
                print('Select a task')
                print('Note: solve the task in a separate program (e.g., PyCharm or VS Code)')
                k = input('Sum calculator for two numbers = 1 / age verification = 2 / counter from 1 to n = 3 / password check = 4 ')
                if k == '1':
                    print('SUM CALCULATOR FOR TWO NUMBERS')
                    print('Task:')
                    print('Write a program that asks the user for two integers and prints their sum.')
                    input('Press Enter to check and get the ready code')
                    print('num1 = int(input("Enter the first number: "))')
                    print('num2 = int(input("Enter the second number: "))')
                    print('result = num1 + num2')
                    print('print("Sum:", result)')
                if k == '2':
                    print('AGE VERIFICATION')
                    print('Task:')
                    print('Create a program that determines whether the user is an adult based on their entered age.')
                    input('Press Enter to check and get the ready code')
                    print('age = int(input("How old are you? "))')
                    print('if age >= 18:')
                    print('     print("You are an adult")')
                    print('else:')
                    print('     print("You are a minor")')
                if k == '3':
                    print('COUNTER FROM 1 TO N')
                    print('Task:')
                    print('Print all numbers from 1 to N, where N is entered by the user.')
                    input('Press Enter to check and get the ready code')
                    print('n = int(input("Enter a number: "))')
                    print('for i in range(1, n + 1):')
                    print('     print(i)')
                if k == '4':
                    print('PASSWORD CHECK')
                    print('Task:')
                    print(
                        'Implement a simple password check — access is allowed only if the correct password is entered.')
                    input('Press Enter to check and get the ready code')
                    print('password = "12345"')
                    print('user_input = input("Enter password: ")')
                    print('if user_input == password:')
                    print('     print("Access granted")')
                    print('else:')
                    print('     print("Wrong password")')
            else:
                print('ERROR')
    if b == '2':
        while True:
            print('Choose a topic')
            c = input('BASIC SYNTAX = 1/VARIABLES AND DATA TYPES = 2/DATA INPUT = 3/#include = 4')
            if c == '1':
                print('BASIC SYNTAX')
                print('Every C++ program consists of required elements.')
                print('First, libraries are included — sets of ready-made functions, for example iostream for input and output.')
                print('Then the namespace std is specified so you don’t have to write it before each command.')
                print('The main part of the program is the main() function, which is executed first.')
                print('All code is written inside the curly braces of this function.')
                print('At the end, the program returns 0, which means successful completion.')
                print('To output information to the screen, the cout command with the << operator is used.')
                print('Text is output in double quotes.')
                print('To move to a new line, endl is used.')
                print('Commands are separated by a semicolon.')
            if c == '2':
                print('VARIABLES AND DATA TYPES')
                print('Variables are named memory cells for storing data.')
                print('Each variable has a type, a name, and a value.')
                print('The type determines what data can be stored and how much space they occupy.')
                print('Main data types:')
                print('Integers: int for regular numbers, short for small ones, long for large ones')
                print('Floating-point numbers: float with normal precision, double with double precision')
                print('Characters: char stores one character in single quotes')
                print('Boolean values: bool stores true or false')
                print('Strings: string stores text in double quotes')
                print('Variable names must start with a letter or underscore, contain only letters, digits, and underscores.')
                print('Case matters.')
            if c == '3':
                print('To get data from the user, the cin command with the >> operator is used.')
                print('The program waits for the user to enter data and press Enter.')
                print('Numbers, characters, and strings can be read.')
                print('When reading strings, there are nuances:')
                print('cin reads only until the first space.')
                print('To read an entire line with spaces, getline() is used.')
                print('Important:')
                print('cin and cout work through a buffer — temporary data storage.')
                print('When entering numbers, be careful because a newline character may remain in the buffer after them.')
            if c == "4":
                print('#include — LIBRARY INCLUSION IN C++')
                print('What: A directive for including external libraries.')
                print('Main features:')
                print('Adds ready-made functions to the program')
                print('Without it, cout, cin, string won’t work')
                print('Written at the very beginning of the file')
                print('Purpose:')
                print('To use standard C++ functions')
                print('To handle input/output')
                print('To add mathematical operations')
                print('To use containers and algorithms')
                print('Important:')
                print('Angle brackets for standard libraries: #include <iostream>')
                print('Quotes for your own files: #include "myfile.h"')
                print('Each library is a separate directive')
                print('Order doesn’t matter, but logical grouping is better')
                print('Examples of libraries:')
                print('<iostream> — input/output')
                print('<string> — string manipulation')
                print('<cmath> — mathematical functions')
                print('<vector> — dynamic arrays')
            else:
                print('ERROR')
    if b == '3':
        while True:
            print('Choose a topic')
            c = input('console.log() = 1/let / const = 2/prompt() / alert() = 3/if - else = 4/ for = 5')
            if c == '1':
                print('console.log() — OUTPUT INFORMATION')
                print('What it is: The very first command learned in JavaScript.')
                print('Used to output information to the browser console or Node.js terminal.')
                print('What it’s for:')
                print('Debugging code (checking variable values)')
                print('Outputting program results')
                print('Error or event messages')
                print('How it works:')
                print('Accepts any number of arguments and outputs them to the console.')
                print('Arguments are converted to strings if necessary.')
                print('Features:')
                print('Does not interrupt program execution')
                print('Can output any data types')
                print('In the browser, opened via Developer Tools (F12)')
            if c == '2':
                print('let / const — DECLARING VARIABLES')
                print('What it is: Keywords for creating variables.')
                print('let — for changeable values, const — for unchangeable ones (constants).')
                print('What they are for:')
                print('Storing data in memory')
                print('Reusing values')
                print('Improving code readability')
                print('How they work:')
                print('let allows changing the variable value')
                print('Scope — code block (curly braces)')
                print('Features:')
                print('var was used earlier (obsolete, has different scope)')
                print('const does not make objects immutable, only protects from reassignment')
                print('Variables must be declared before use')
            if c == '3':
                print('prompt() / alert() — INTERACTING WITH THE USER')
                print('What it is: Commands for simple dialogue with the user in the browser.')
                print('alert() — displaying a message:')
                print('Shows a modal window with a message')
                print('The user must press OK to continue')
                print('Used for important notifications')
                print('prompt() — inputting data:')
                print('Shows a window with a field for entering text')
                print('Returns the entered string or null if canceled')
                print('Always returns a string, even if a number is entered')
                print('What they are for:')
                print('Quick testing of interaction')
                print('Simplest input forms')
                print('Demonstration examples')
                print('Features:')
                print('Block JavaScript execution until the user responds')
                print('Design depends on the browser')
                print('Rarely used in real projects (HTML forms are preferred)')
            if c == '4':
                print('if...else — CONDITIONS IN JAVASCRIPT')
                print('What: A construct for making decisions in code.')
                print('Why: To make the program execute different code depending on the situation.')
                print('How:')
                print('if checks a condition')
                print('If the condition is true → code in {} is executed')
                print('If false and there is else → code after else is executed')
                print('Chain possible: if → else if → else')
                print('Features:')
                print('=== compares strictly (type and value)')
                print('== compares with type conversion')
                print('&& (AND), || (OR), ! (NOT) for complex conditions')
                print('Why important:')
                print('Without conditions, code is only linear.')
                print('With if...else, the program becomes "smart" and reacts to data.')
            if c == '5':
                print('for — ITERATION LOOP IN JAVASCRIPT')
                print('What: A loop for sequentially iterating over elements.')
                print('Main features:')
                print('Iterates over arrays, strings, objects')
                print('Works with iterators (lists of elements)')
                print('Automatically goes through all elements from start to end')
                print('Purpose:')
                print('To process each array element')
                print('To traverse all characters in a string')
                print('To perform an action for a dataset')
                print('To automate repetitive operations')
                print('Important:')
                print('Do not confuse with for in C++/Python — the syntax is different')
                print('More commonly used for arrays than while')
                print('Can be interrupted with break or skip an iteration with continue')
            else:
                print('ERROR')
    else:
        print('ERROR')
else:
    print('ERROR')
#Here a person looking at the code might have a question: why are there so many print() statements?
#I know that end = "\n" exists
#First, for a beginner, it will be easier to understand the meaning of print() and input() in this format
#Second
#I like the code better this way
