print("Select a language/Выберите язык")
a = input('Eng=2/Рус=1:')
if a == '1':
    print('Выберите язык программирования, азы которого вы хотите узнать')
    b = input('Python = 1/C++ = 2/JavaScript = 3')
    if b == '1':
        while True:
            print('Выберите тему')
            c = input('print() = 1/input() = 2/While = 3')
            if c == '1':
                print('print() — Вывод информации на экран')
                print('Зачем нужен? Чтобы программа показывала текст, числа или результаты вычислений.')
                print('Как работает? Вы пишете print(), а внутрь скобок помещаете то, что хотите вывести.')
                print('Простые примеры:')
                print('print(2026)')
                print('Несколько значений сразу: Перечислите их через запятую.')
                print('Соединение текста (конкатенация): Используйте +, но не смешивайте строки и числа.')
            if c == 2:
                input('Заметим, что в каждой теме используется именно та команда, тема которой изучается. Для продолжения нажмите Enter')
                input('input() — Ввод информации от пользователя')
                input('Зачем нужен? Чтобы программа могла спросить что-то у пользователя и запомнить ответ.')
                input('Как работает? Программа ставится на паузу, ждет, пока пользователь введет текст и нажмет Enter. Введенные данные всегда возвращаются в виде строки (text).')
                input('Простой пример:')
                input('user_name = input("Как тебя зовут? ")')
                input('print("Рад познакомиться, " + user_name + "!")')
                input('Важное правило:')
                input('input() всегда возвращает строку. Даже если вы ввели число.')
                input('age = input("Сколько тебе лет? ")')
                input('print(type(age))')
                input('age_number = int(age)')
                input('print("В следующем году тебе будет", age_number + 1)')
                input('Можно сразу преобразовать ввод:')
                input('age = int(input("Сколько тебе лет? "))')
            if c == 3:
                print('Заметим, что весь код зациклен имеенно while True')
                print('while — Цикл «Пока»')
                print('Зачем нужен? Чтобы повторять один и тот же блок кода много раз, пока выполняется какое-то условие.')
                print('Как работает? Пока условие после слова while истинно (True), команды внутри цикла выполняются снова и снова.')
            else:
                print('ERROR')
    if b == 2:
        while True:
            print('Выберите тему')
            c = input('БАЗОВЫЙ СИНТАКСИС = 1/ПЕРЕМЕННЫЕ И ТИПЫ ДАННЫХ = 2/ВВОД ДАННЫХ = 3')
            if c == 1:
                print('БАЗОВЫЙ СИНТАКСИС')
                print('Каждая программа на C++ состоит из обязательных элементов.')
                print('Сначала подключаются библиотеки — наборы готовых функций, например iostream для ввода и вывода.')
                print('Затем указывается пространство имен std, чтобы не писать его перед каждой командой.')
                print('Главная часть программы — функция main(), которая выполняется первой.')
                print('Весь код пишется внутри фигурных скобок этой функции.')
                print('В конце программа возвращает 0, что означает успешное завершение.')
                print('Для вывода информации на экран используется команда cout с оператором <<.')
                print('Текст выводится в двойных кавычках.')
                print('Для перехода на новую строку используется endl.')
                print('Команды разделяются точкой с запятой.')
            if c == 2:
                print('ПЕРЕМЕННЫЕ И ТИПЫ ДАННЫХ')
                print('Переменные — это именованные ячейки памяти для хранения данных.')
                print('Каждая переменная имеет тип, имя и значение.')
                print('Тип определяет, какие данные можно хранить и сколько места они занимают.')
                print('Основные типы данных:')
                print('Целые числа: int для обычных чисел, short для маленьких, long для больших')
                print('Дробные числа: float с обычной точностью, double с двойной точностью')
                print('Символы: char хранит один символ в одинарных кавычках')
                print('Логические значения: bool хранит true (истина) или false (ложь)')
                print('Строки: string хранит текст в двойных кавычках')
                print('Имена переменных должны начинаться с буквы или подчеркивания, содержать только буквы, цифры и подчеркивания.')
                print('Содержать только буквы, цифры и подчеркивания. Регистр имеет значение.')
            if c == 3:
                print('Для получения данных от пользователя используется команда cin с оператором >>.')
                print('Программа ждет, пока пользователь введет данные и нажмет Enter.')
                print('Можно считывать числа, символы и строки.')
                print('При считывании строк есть нюансы:')
                print('cin считывает только до первого пробела.')
                print('Для чтения целой строки с пробелами используется getline().')
                print('Важно:')
                print('cin и cout работают через буфер — временное хранилище данных.')
                print('При вводе чисел нужно быть внимательным, так как после них в буфере может оставаться символ новой строки.')
            else:
                print('ERROR')
#Тут у человека смотрящего код может созреть вопрос почему так много print().
#Я знаю, что сущесвтует end = "\n"
#Во первых новичку в таком формате будет проще понять смысл print() и input()
#Во вторых
#В таком виде код мне нравится больше
    if b == 3:
        while True:
            print('Выберите тему')
            c = input('console.log() = 1/let / const = 2/prompt() / alert() = 3')
            if c == 1:
                print('console.log() — ВЫВОД ИНФОРМАЦИИ')
                print('Что это: Самая первая команда, которую изучают в JavaScript.')
                print('Служит для вывода информации в консоль браузера или терминал Node.js.')
                print('Зачем нужна:')
                print('Отладка кода (проверка значений переменных)')
                print('Вывод результатов работы программы')
                print('Сообщения об ошибках или событиях')
                print('Как работает:')
                print('Принимает любое количество аргументов и выводит их в консоль.')
                print('Аргументы преобразуются в строки, если это необходимо.')
                print('Особенности:')
                print('Не прерывает выполнение программы')
                print('Может выводить любые типы данных')
                print('В браузере открывается через Инструменты разработчика (F12)')
            if c == 2:
                print('let / const — ОБЪЯВЛЕНИЕ ПЕРЕМЕННЫХ')
                print('Что это: Ключевые слова для создания переменных.')
                print('let — для изменяемых значений, const — для неизменяемых (констант).')
                print('Зачем нужны:')
                print('Хранение данных в памяти')
                print('Повторное использование значений')
                print('Улучшение читаемости кода')
                print('Как работают:')
                print('let позволяет менять значение переменной')
                print('Область видимости — блок кода (фигурные скобки)')
                print('Особенности:')
                print('Раньше использовался var (устаревший, имеет другую область видимости)')
                print('const не делает объекты неизменяемыми, только защищает от переприсваивания')
                print('Переменные объявляются до использования')
            if c == 3:
                print('prompt() / alert() — ВЗАИМОДЕЙСТВИЕ С ПОЛЬЗОВАТЕЛЕМ')
                print('Что это: Команды для простого диалога с пользователем в браузере.')
                print('alert() — вывод сообщения:')
                print('Показывает модальное окно с сообщением')
                print('Пользователь должен нажать OK для продолжения')
                print('Используется для важных уведомлений')
                print('prompt() — ввод данных:')
                print('Показывает окно с полем для ввода текста')
                print('Возвращает введенную строку или null при отмене')
                print('Всегда возвращает строку, даже если введено число')
                print('Зачем нужны:')
                print('Быстрое тестирование взаимодействия')
                print('Простейшие формы ввода')
                print('Демонстрационные примеры')
                print('Особенности:')
                print('Блокируют выполнение JavaScript до ответа пользователя')
                print('Дизайн зависит от браузера')
                print('В реальных проектах используются редко (предпочитают HTML-формы)')
            else:
                print('ERROR')
    else:
        print('ERROR')

if a == '2':
    print('Choose a programming language you want to learn the basics of')
    b = input('Python = 1/C++ = 2/JavaScript = 3')
    if b == '1':
        while True:
            print('Choose a topic')
            c = input('print() = 1/input() = 2/While = 3')
            if c == '1':
                print('print() — Outputting information to the screen')
                print('What is it for? To make the program display text, numbers, or calculation results.')
                print('How does it work? You write print(), and inside the parentheses you put what you want to output.')
                print('Simple examples:')
                print('print(2026)')
                print('Multiple values at once: List them separated by commas.')
                print('Text concatenation: Use +, but do not mix strings and numbers.')
            if c == 2:
                input('Note that each topic uses the command that is being studied. Press Enter to continue')
                input('input() — Getting input from the user')
                input('What is it for? So that the program can ask the user something and remember the answer.')
                input('How does it work? The program pauses, waits for the user to enter text and press Enter. The entered data is always returned as a string (text).')
                input('Simple example:')
                input('user_name = input("What is your name? ")')
                input('print("Nice to meet you, " + user_name + "!")')
                input('Important rule:')
                input('input() always returns a string. Even if you entered a number.')
                input('age = input("How old are you? ")')
                input('print(type(age))')
                input('age_number = int(age)')
                input('print("Next year you will be", age_number + 1)')
                input('You can convert input immediately:')
                input('age = int(input("How old are you? "))')
            if c == 3:
                print('Note that the entire code is looped with while True')
                print('while — The "While" Loop')
                print('What is it for? To repeat the same block of code many times as long as some condition is true.')
                print('How does it work? As long as the condition after the word while is true (True), the commands inside the loop are executed again and again.')
            else:
                print('ERROR')
    if b == 2:
        while True:
            print('Choose a topic')
            c = input('BASIC SYNTAX = 1/VARIABLES AND DATA TYPES = 2/DATA INPUT = 3')
            if c == 1:
                print('BASIC SYNTAX')
                print('Every C++ program consists of required elements.')
                print('First, libraries are included — sets of ready-made functions, for example iostream for input and output.')
                print('Then the namespace std is specified so you don’t have to write it before each command.')
                print('The main part of the program is the main() function, which is executed first.')
                print('All code is written inside the curly braces of this function.')
                print('At the end, the program returns 0, which means successful completion.')
                print('To output information to the screen, the cout command with the << operator is used.')
                print('Text is output in double quotes.')
                print('To move to a new line, endl is used.')
                print('Commands are separated by a semicolon.')
            if c == 2:
                print('VARIABLES AND DATA TYPES')
                print('Variables are named memory cells for storing data.')
                print('Each variable has a type, a name, and a value.')
                print('The type determines what data can be stored and how much space they occupy.')
                print('Main data types:')
                print('Integers: int for regular numbers, short for small ones, long for large ones')
                print('Floating-point numbers: float with normal precision, double with double precision')
                print('Characters: char stores one character in single quotes')
                print('Boolean values: bool stores true or false')
                print('Strings: string stores text in double quotes')
                print('Variable names must start with a letter or underscore, contain only letters, digits, and underscores.')
                print('Case matters.')
            if c == 3:
                print('To get data from the user, the cin command with the >> operator is used.')
                print('The program waits for the user to enter data and press Enter.')
                print('Numbers, characters, and strings can be read.')
                print('When reading strings, there are nuances:')
                print('cin reads only until the first space.')
                print('To read an entire line with spaces, getline() is used.')
                print('Important:')
                print('cin and cout work through a buffer — temporary data storage.')
                print('When entering numbers, be careful because a newline character may remain in the buffer after them.')
            else:
                print('ERROR')
    if b == 3:
        while True:
            print('Choose a topic')
            c = input('console.log() = 1/let / const = 2/prompt() / alert() = 3')
            if c == 1:
                print('console.log() — OUTPUT INFORMATION')
                print('What it is: The very first command learned in JavaScript.')
                print('Used to output information to the browser console or Node.js terminal.')
                print('What it’s for:')
                print('Debugging code (checking variable values)')
                print('Outputting program results')
                print('Error or event messages')
                print('How it works:')
                print('Accepts any number of arguments and outputs them to the console.')
                print('Arguments are converted to strings if necessary.')
                print('Features:')
                print('Does not interrupt program execution')
                print('Can output any data types')
                print('In the browser, opened via Developer Tools (F12)')
            if c == 2:
                print('let / const — DECLARING VARIABLES')
                print('What it is: Keywords for creating variables.')
                print('let — for changeable values, const — for unchangeable ones (constants).')
                print('What they are for:')
                print('Storing data in memory')
                print('Reusing values')
                print('Improving code readability')
                print('How they work:')
                print('let allows changing the variable value')
                print('Scope — code block (curly braces)')
                print('Features:')
                print('var was used earlier (obsolete, has different scope)')
                print('const does not make objects immutable, only protects from reassignment')
                print('Variables must be declared before use')
            if c == 3:
                print('prompt() / alert() — INTERACTING WITH THE USER')
                print('What it is: Commands for simple dialogue with the user in the browser.')
                print('alert() — displaying a message:')
                print('Shows a modal window with a message')
                print('The user must press OK to continue')
                print('Used for important notifications')
                print('prompt() — inputting data:')
                print('Shows a window with a field for entering text')
                print('Returns the entered string or null if canceled')
                print('Always returns a string, even if a number is entered')
                print('What they are for:')
                print('Quick testing of interaction')
                print('Simplest input forms')
                print('Demonstration examples')
                print('Features:')
                print('Block JavaScript execution until the user responds')
                print('Design depends on the browser')
                print('Rarely used in real projects (HTML forms are preferred)')
            else:
                print('ERROR')
    else:
        print('ERROR')
else:
    print('ERROR')
#Here a person looking at the code might have a question: why are there so many print() statements?
#I know that end = "\n" exists
#First, for a beginner, it will be easier to understand the meaning of print() and input() in this format
#Second
#I like the code better this way
